---
title: "Probability Distribution"
output: learnr::tutorial
runtime: shiny_prerendered

---

```{r setup, include=FALSE}
library(learnr)
library(shiny)
library(tidyverse)
library(plotly)
library(shinyjs)
library(rsconnect)
theme_set(theme_bw())
knitr::opts_chunk$set(echo = FALSE)
```
### Exercise

You need to generate *Y* that represents the post-treatment scores for our sample of 100 students，if the program is not implemented.
Write the code to generate the post-treatment scores. You shall check the hint if you are unfamiliar with R functions:

```{r frq, exercise=TRUE, exercise.eval=TRUE}

```

```{r frq-hint}
Y<-rnorm(n = 100, mean = ..., sd = ...)
print(Y)
```

```{r frq-solution}
#This is just one example of simulating Y; You shall pick any reasonable expected average post-treatment score and the standard deviation
Y<-rnorm(n = 100, mean = 60, sd = 5)
print(Y)

 
#r frq-code-check
#grade_code()
#I delete the code check section, since we would like the students to simulate the dataset as they wish.
```

```{r quiz}
quiz(
  question("Which of following is not an example of continuous variable  :",
    answer("Age of students"),
    answer("Race of students", correct = TRUE),
    answer("Grade of students", correct = TRUE),
    answer("Commute time of students")
  )
)
```


